### ISSUE TITLE
Relationship between Simulation L,U and velocity, length in reality

### ISSUE THREAD

**Issue by zchli9** [WaterLily-jl/WaterLily.jl#175]
How do the length scale $L$ and velocity scales $U$ and $\nu$ in the simulation relate to velocity, length and kinematic viscosity in reality?  For example, I want to simulate a water flow ($\nu$ = $1e-6$) with a speed of $3m/s$ impacting a cylinder with a diameter of $0.5m$ and a height of $5m$. The water tank is $10m$ * $10m$ * $10m$, and the cylinder is placed in the middle. How should I set the parameters？
Thank you!

**Comment by b-fg** [comment]
You should first *define* the length and velocity scales. For example, if you pick the cylinder diameter as length scale, then your domain is `20*(D,D,D)`. If you pick the free-stream velocity as velocity scale, `U=U∞`, then your viscosity is `ν=U∞*D/Re` where `Re=1.5e6` from your dimensional data and `D` is the number of cells you want to use to discretize the cylinder diameter (the overall simulation resolution). Ultimately you define a scaled viscosity according to the target Reynolds number and the desired resolution.

```julia
Re = 1.5e6
D = 8
box = (20*D, 20*D, 20*D)
U∞ = 3
ν = U∞*D/Re

# Define cylinder distance function
function cylinder(...) ... end

sim = Simulation(box, (U∞, 0, 0), D; U=U∞, exitBC=true, body=cylinder)
```

However 2 things to note:
- the resolution in the example above is very low (only 8 cells per diameter) and you have a large domain and a very high Reynolds number. With a more realistic resolution of (eg) 64 cells per diameter (still quite low for a turbulent BL), this results in a total of 2 billion cells... which is unfeasible because of memory requirements and because we do not have MPI implemented yet.
- It is typically better to define the domain size as a power of 2, and then compute the resolution accordingly. This result in more efficient computations on GPUs and helps the multi-grid solver.

**Comment by zchli9** [comment]
Thanks！So if the Reynolds number and the ratio of the cylinder to the water tank are determined, the physical properties of the real situation represented by the simulation are consistent? Maybe I'm still a little confused about the velocity scale.For example：
Simulation1：water speed 0.1m/s , cylinder diameter 10m , water tank length 128m*128m*128m
Simulation2：water speed 10m/s , cylinder diameter 0.1m , water tank length 1.28m*1.28m*1.28m
the physical properties of the real-life situation is the same?
The number may not be reasonable, I'm just giving an example. I can use the same code `Simulation(box, (U, 0, 0), D; U=U, exitBC=true, body=cylinder)`with Re = 1e6, U=1, D=10, ν = U*D/Re. Right? Sorry I'm not familiar with fluid mechanics.

**Comment by b-fg** [comment]
The Reynolds number would be the same, and that's what we use to estimate the resolution of a simulation. Correct on the last question.
