### ISSUE TITLE
Problem with simulation for flow over cylinder

### ISSUE THREAD

**Issue by vvn29** [WaterLily-jl/WaterLily.jl#186]
I ran a simulation on Waterlily, for flow over cylinder with parameters: Diameter, m/4, Domain size: 16*m X 24*m, m= 2^6 and U =1., Re = 100. I am getting mean Cd value around 1, which is quite off from the benchmark values. I have pasted the entire code. Can anyone help me understand what I am doing wrong.  The code is almost the same as the example code in the repository with small changes.

Also I am not able to understand how to specify the grid size, is it just automatically changing with the increase in domain and Resolution( I assume the m value that i define in the code). Also are there other ways to explicitly define the boundary conditions, such as no slip, etc
Thank you

#############################The code that i used####################################
```julia
using WaterLily, CUDA, Statistics, Plots
include("../src/TwoD_plots.jl")

# Function to create the simulation
function circle(m;Re=100,U=1)
    # signed distance function to circle
    radius = m / 8
    center = (2m, 2m)
    sdf(x,t) = √sum(abs2, x .- center) - radius

    Simulation((6m,4m),   # domain size
               (U,0),   # domain velocity (& velocity scale)
               2radius; # length scale
               ν=U*2radius/Re,     # fluid viscosity
               body=AutoBody(sdf), mem=CuArray) # geometry
end

# Function to get forces on the CPU
function get_forces!(sim,t)
    sim_step!(sim,t,remeasure=false)
    CUDA.@allowscalar begin
        force = WaterLily.pressure_force(sim)
    end 
    return force./((0.5sim.L*sim.U^2))
end

# Function to visualize thrust coefficients
function visualize_sdf(time, forces)
    plot(time, forces,
         xlabel="Time",
         ylabel="Thrust coefficients")
end

@assert CUDA.functional()
sim = circle(2^6)

time = 50:0.5:100.0

forces = [get_forces!(sim, t) for t in time];

drag_coefficients = [force[1] for force in forces]  # First element of each inner array
lift_coefficients = [force[2] for force in forces]  # Second element of each inner array


# Calculate mean thrust coefficient for drag


lift_plot = plot(time,[first.(forces), last.(forces)],
    labels=permutedims(["drag","lift"]),
    xlabel="tU/L",
    ylabel="Pressure force coefficients")

savefig(lift_plot, "cylinder_ld_coarse_2.png")

open("coefficients_2.6.txt", "w") do io
    # Write a header for clarity (optional)
    println(io, "Time Drag_Coefficient Lift_Coefficient")
    
    # Write each time step and coefficients
    for (t, drag, lift) in zip(time, drag_coefficients, lift_coefficients)
        println(io, "$t $drag $lift")
    end
end
# Generate simulation gif
sim_gif!(sim, duration=50, step =0.1, clims=(-5, 5), plotbody=true)

Ct_mean_drag = mean(drag_coefficients)
println("Mean Drag Coefficient (Ct_drag): ", Ct_mean_drag)

# Calculate mean thrust coefficient for lift
Ct_mean_lift = mean(lift_coefficients)
println("Mean Lift Coefficient (Ct_lift): ", Ct_mean_lift)
```

**Comment by weymouth** [comment]
A pressure force coefficient of $C_{Dp}=1$ is exactly the right value. See [Maertens 2015](https://eprints.soton.ac.uk/369635/1/Maertens2014%2520CMAME.pdf). Perhaps you want total force (which should be $C_D\approx 1.25-1.35$) instead of the pressure force. In that case, just use `force=WaterLily.total_force(sim)`. To accurately resolve the friction force, you'll likely need a finer grid. Right now you only have radius=8 cells, which is really really tiny. You increase the resolution by increasing `m` in your script. (By the way, I'm not sure what `m` is supposed to be in your script. It's probably better to make `n,m` the size of the domain to avoid getting confused. Then just set `radius=m/32` and `n=3m÷2` to recover your current results.) Get your radius up towards the values in that reference above (Table 1 uses radius=60 cells) and you should reproduces the total forces very accurately.

**Comment by vvn29** [comment]
Thank you very much for your help
